project:
  type: website
  output-dir: docs

website:
  title: "Anya's Website! "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: STAT-244-SC.qmd
        text: STAT244-SC
      

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

